name: Email Flow QA Tests

# Trigger on pushes to main and all pull requests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    # Also trigger on specific paths that affect email functionality
    paths:
      - 'backend/**'
      - '.github/workflows/email-flow-qa.yml'

# Allow manual triggering for testing
  workflow_dispatch:

jobs:
  email-flow-tests:
    name: Email Flow QA Tests
    runs-on: ubuntu-latest
    
    # Set up MongoDB service for testing
    services:
      mongodb:
        image: mongo:7.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ping: 1})'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Install Python dependencies
      run: |
        cd backend
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-mock pytest-cov

    - name: Install MongoDB tools
      # Install mongosh (MongoDB shell) using MongoDB's official repository
      run: |
        echo "Installing MongoDB tools from official repository..."
        
        # Import MongoDB public GPG key
        curl -fsSL https://pgp.mongodb.com/server-7.0.asc | \
          sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor
        
        # Add MongoDB repository
        echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | \
          sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
        
        # Update package list and install mongosh
        sudo apt-get update
        sudo apt-get install -y mongodb-mongosh
        
        # Verify installation
        if command -v mongosh &> /dev/null; then
          echo "✅ MongoDB tools installed successfully from official repository"
          mongosh --version
        else
          echo "❌ MongoDB tools installation failed"
          exit 1
        fi

    - name: Wait for MongoDB to be ready
      run: |
        for i in {1..30}; do
          if mongosh --host localhost:27017 --eval "db.runCommand({ping: 1})" --quiet; then
            echo "MongoDB is ready"
            break
          fi
          echo "Waiting for MongoDB... ($i/30)"
          sleep 2
        done

    - name: Test MongoDB connection
      run: |
        mongosh --host localhost:27017 --eval "
          db.test.insertOne({test: 'connection'});
          print('MongoDB connection successful');
          db.test.drop();
        "

    - name: Run email flow regression tests
      run: |
        cd backend
        pytest tests/test_email_data_processing_regression.py -v --tb=short
      env:
        MONGO_URI: mongodb://localhost:27017
        MONGO_DB_NAME: pm_copilot_test
        # Mock environment variables for testing - prevent external API calls
        COMPOSIO_API_KEY: test_key_for_mocking
        OPENAI_API_KEY: test_key_for_mocking
        ANTHROPIC_API_KEY: test_key_for_mocking
        GOOGLE_API_KEY: test_key_for_mocking
        PINECONE_API_TOKEN: test_key_for_mocking
        # Set test environment to prevent external service calls
        TESTING: true
        CI: true

    - name: Run email count verification tests
      run: |
        cd backend
        pytest tests/test_email_count_verification.py -v --tb=short
      env:
        MONGO_URI: mongodb://localhost:27017
        MONGO_DB_NAME: pm_copilot_test
        COMPOSIO_API_KEY: test_key_for_mocking
        OPENAI_API_KEY: test_key_for_mocking
        ANTHROPIC_API_KEY: test_key_for_mocking
        GOOGLE_API_KEY: test_key_for_mocking
        PINECONE_API_TOKEN: test_key_for_mocking
        TESTING: true
        CI: true

    - name: Run email integration flow tests
      run: |
        cd backend
        pytest tests/test_email_integration_flow.py -v --tb=short
      env:
        MONGO_URI: mongodb://localhost:27017
        MONGO_DB_NAME: pm_copilot_test
        COMPOSIO_API_KEY: test_key_for_mocking
        OPENAI_API_KEY: test_key_for_mocking
        ANTHROPIC_API_KEY: test_key_for_mocking
        GOOGLE_API_KEY: test_key_for_mocking
        PINECONE_API_TOKEN: test_key_for_mocking
        TESTING: true
        CI: true

    - name: Run all email tests with coverage
      run: |
        cd backend
        pytest tests/test_email_*.py --cov=models --cov=services --cov-report=xml --cov-report=term-missing
      env:
        MONGO_URI: mongodb://localhost:27017
        MONGO_DB_NAME: pm_copilot_test
        COMPOSIO_API_KEY: test_key_for_mocking
        OPENAI_API_KEY: test_key_for_mocking
        ANTHROPIC_API_KEY: test_key_for_mocking
        GOOGLE_API_KEY: test_key_for_mocking
        PINECONE_API_TOKEN: test_key_for_mocking
        TESTING: true
        CI: true

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: success()
      with:
        file: ./backend/coverage.xml
        flags: email-flow-tests
        name: email-flow-coverage

    - name: Test summary
      run: |
        echo "✅ All email flow QA tests completed successfully!"
        echo "🔍 Tests covered:"
        echo "  - Data structure regression tests (the fix we implemented)"
        echo "  - Email count verification (retrieval vs. saved)"
        echo "  - Full integration flow tests"
        echo "  - Error handling and edge cases"
        echo "  - Performance with large email batches"
        echo "  - All external API calls properly mocked for CI/CD"

  # Job to check if tests are required (for PR status checks)
  email-tests-required:
    name: Email Tests Status Check
    runs-on: ubuntu-latest
    needs: email-flow-tests
    if: always()
    steps:
    - name: Check test results
      run: |
        if [ "${{ needs.email-flow-tests.result }}" = "success" ]; then
          echo "✅ All email flow tests passed!"
          exit 0
        else
          echo "❌ Email flow tests failed!"
          echo "This indicates a potential regression in email functionality."
          echo "Please review the test failures before merging."
          exit 1
        fi

