name: Test MongoDB Tools Installation

# Manual trigger only for testing
on:
  workflow_dispatch:

jobs:
  test-mongodb-install:
    name: Test MongoDB Tools Installation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install MongoDB tools
      # Test the MongoDB tools installation method
      run: |
        echo "Testing MongoDB tools installation from official repository..."
        
        # Import MongoDB public GPG key
        curl -fsSL https://pgp.mongodb.com/server-7.0.asc | \
          sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor
        
        # Add MongoDB repository
        echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | \
          sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
        
        # Update package list and install mongosh
        sudo apt-get update
        sudo apt-get install -y mongodb-mongosh
        
        # Verify installation
        if command -v mongosh &> /dev/null; then
          echo "✅ MongoDB tools installed successfully from official repository"
          mongosh --version
        else
          echo "❌ MongoDB tools installation failed"
          exit 1
        fi

    - name: Test MongoDB connection
      run: |
        echo "Testing mongosh command..."
        mongosh --eval "print('MongoDB shell is working correctly')" --quiet
        
        echo "✅ MongoDB tools installation test completed successfully!"
